name: Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run Tests + JaCoCo
        run: mvn clean test jacoco:report

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=LibraryManagementSystem-SE_SE
            -Dsonar.organization=librarymanagementsystem-se
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.coverage.exclusions=**/gui/**,**/system/**,**/repository/**,**/domain/**,**/notification/**,**/*Application.java,**/*CLI.java,**/*Main.java
            -Dsonar.cpd.exclusions=**/gui/**,**/repository/**,**/domain/**,**/notification/**,**/test/**
